# Dockerfile.prod

# Base image
FROM eclipse-temurin:21-jdk

# Set working directory
WORKDIR /app

# CI/CD에서 빌드된 JAR 파일만 복사
COPY build/libs/*-SNAPSHOT.jar app.jar

# Expose application port
EXPOSE 8080

# Run the application with AWS profile
ENTRYPOINT ["java", "-Dspring.profiles.active=aws", "-jar", "app.jar"]
